-- MySQL Script generated by MySQL Workbench
-- Thu 13 Oct 2016 07:30:50 PM NPT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `created_at` TIMESTAMP(6) NULL,
  `updated_at` TIMESTAMP(6) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone` DECIMAL(10,0) NULL,
  `address` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `blood_group` VARCHAR(45) NULL,
  `user_type_id` INT NULL,
  `created_at` TIMESTAMP(6) NULL,
  `updated_at` TIMESTAMP(6) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `mydb`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `username_UNIQUE` ON `mydb`.`users` (`username` ASC);

CREATE UNIQUE INDEX `email_UNIQUE` ON `mydb`.`users` (`email` ASC);

CREATE INDEX `fk_users_1_idx` ON `mydb`.`users` (`user_type_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`donations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`donations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `donor_id` INT NULL,
  `reciever_id` INT NULL,
  `created_at` TIMESTAMP(6) NULL,
  `updated_at` TIMESTAMP(6) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`donations_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`donations_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `donations_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `created_at` TIMESTAMP(6) NULL,
  `deleted_at` TIMESTAMP(6) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_donations_has_users_donations`
    FOREIGN KEY (`donations_id`)
    REFERENCES `mydb`.`donations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_donations_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_donations_has_users_users1_idx` ON `mydb`.`donations_users` (`users_id` ASC);

CREATE INDEX `fk_donations_has_users_donations_idx` ON `mydb`.`donations_users` (`donations_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
